[package]
name = "math-once"
version = "0.20.0"
entrypoint = "math-once.typ"
authors = ["Mikkel"]
license = "MIT"
description = "Reusable calculations with physical units, automatic conversion, and visible equations."
categories = ["utility"]
compiler = "0.14.0"
