// Generated from codex 0.2.0's mathematical symbol sections.
// Regenerate with tools/generate-symbol-catalog.py; do not edit by hand.
#import "../math-once.typ": calculation-builder

#let eq = calculation-builder(key: "all-mathematical-symbols")
#let symbols = (
  ("plus", "+"),
  ("plus.o", "⊕"),
  ("plus.o.l", "⨭"),
  ("plus.o.r", "⨮"),
  ("plus.o.arrow", "⟴"),
  ("plus.o.big", "⨁"),
  ("plus.dot", "∔"),
  ("plus.double", "⧺"),
  ("plus.minus", "±"),
  ("plus.square", "⊞"),
  ("plus.triangle", "⨹"),
  ("plus.triple", "⧻"),
  ("minus", "−"),
  ("minus.o", "⊖"),
  ("minus.dot", "∸"),
  ("minus.plus", "∓"),
  ("minus.square", "⊟"),
  ("minus.tilde", "≂"),
  ("minus.triangle", "⨺"),
  ("div", "÷"),
  ("div.o", "⨸"),
  ("div.slanted.o", "⦼"),
  ("times", "×"),
  ("times.big", "⨉"),
  ("times.o", "⊗"),
  ("times.o.l", "⨴"),
  ("times.o.r", "⨵"),
  ("times.o.hat", "⨶"),
  ("times.o.big", "⨂"),
  ("times.div", "⋇"),
  ("times.three.l", "⋋"),
  ("times.three.r", "⋌"),
  ("times.l", "⋉"),
  ("times.r", "⋊"),
  ("times.square", "⊠"),
  ("times.triangle", "⨻"),
  ("ratio", "∶"),
  ("eq", "="),
  ("eq.star", "≛"),
  ("eq.o", "⊜"),
  ("eq.colon", "≕"),
  ("eq.dots", "≑"),
  ("eq.dots.down", "≒"),
  ("eq.dots.up", "≓"),
  ("eq.def", "≝"),
  ("eq.delta", "≜"),
  ("eq.equi", "≚"),
  ("eq.est", "≙"),
  ("eq.gt", "⋝"),
  ("eq.lt", "⋜"),
  ("eq.m", "≞"),
  ("eq.not", "≠"),
  ("eq.prec", "⋞"),
  ("eq.quest", "≟"),
  ("eq.succ", "⋟"),
  ("eq.triple", "≡"),
  ("eq.triple.not", "≢"),
  ("eq.quad", "≣"),
  ("gt", ">"),
  ("gt.o", "⧁"),
  ("gt.dot", "⋗"),
  ("gt.approx", "⪆"),
  ("gt.double", "≫"),
  ("gt.eq", "≥"),
  ("gt.eq.slant", "⩾"),
  ("gt.eq.lt", "⋛"),
  ("gt.eq.not", "≱"),
  ("gt.equiv", "≧"),
  ("gt.lt", "≷"),
  ("gt.lt.not", "≹"),
  ("gt.neq", "⪈"),
  ("gt.napprox", "⪊"),
  ("gt.nequiv", "≩"),
  ("gt.not", "≯"),
  ("gt.ntilde", "⋧"),
  ("gt.tilde", "≳"),
  ("gt.tilde.not", "≵"),
  ("gt.tri", "⊳"),
  ("gt.tri.eq", "⊵"),
  ("gt.tri.eq.not", "⋭"),
  ("gt.tri.not", "⋫"),
  ("gt.triple", "⋙"),
  ("gt.triple.nested", "⫸"),
  ("lt", "<"),
  ("lt.o", "⧀"),
  ("lt.dot", "⋖"),
  ("lt.approx", "⪅"),
  ("lt.double", "≪"),
  ("lt.eq", "≤"),
  ("lt.eq.slant", "⩽"),
  ("lt.eq.gt", "⋚"),
  ("lt.eq.not", "≰"),
  ("lt.equiv", "≦"),
  ("lt.gt", "≶"),
  ("lt.gt.not", "≸"),
  ("lt.neq", "⪇"),
  ("lt.napprox", "⪉"),
  ("lt.nequiv", "≨"),
  ("lt.not", "≮"),
  ("lt.ntilde", "⋦"),
  ("lt.tilde", "≲"),
  ("lt.tilde.not", "≴"),
  ("lt.tri", "⊲"),
  ("lt.tri.eq", "⊴"),
  ("lt.tri.eq.not", "⋬"),
  ("lt.tri.not", "⋪"),
  ("lt.triple", "⋘"),
  ("lt.triple.nested", "⫷"),
  ("approx", "≈"),
  ("approx.eq", "≊"),
  ("approx.not", "≉"),
  ("prec", "≺"),
  ("prec.approx", "⪷"),
  ("prec.curly.eq", "≼"),
  ("prec.curly.eq.not", "⋠"),
  ("prec.double", "⪻"),
  ("prec.eq", "⪯"),
  ("prec.equiv", "⪳"),
  ("prec.napprox", "⪹"),
  ("prec.neq", "⪱"),
  ("prec.nequiv", "⪵"),
  ("prec.not", "⊀"),
  ("prec.ntilde", "⋨"),
  ("prec.tilde", "≾"),
  ("succ", "≻"),
  ("succ.approx", "⪸"),
  ("succ.curly.eq", "≽"),
  ("succ.curly.eq.not", "⋡"),
  ("succ.double", "⪼"),
  ("succ.eq", "⪰"),
  ("succ.equiv", "⪴"),
  ("succ.napprox", "⪺"),
  ("succ.neq", "⪲"),
  ("succ.nequiv", "⪶"),
  ("succ.not", "⊁"),
  ("succ.ntilde", "⋩"),
  ("succ.tilde", "≿"),
  ("equiv", "≡"),
  ("equiv.not", "≢"),
  ("smt", "⪪"),
  ("smt.eq", "⪬"),
  ("lat", "⪫"),
  ("lat.eq", "⪭"),
  ("prop", "∝"),
  ("original", "⊶"),
  ("image", "⊷"),
  ("asymp", "≍"),
  ("asymp.not", "≭"),
  ("emptyset", "∅"),
  ("emptyset.arrow.r", "⦳"),
  ("emptyset.arrow.l", "⦴"),
  ("emptyset.bar", "⦱"),
  ("emptyset.circle", "⦲"),
  ("emptyset.rev", "⦰"),
  ("nothing", "∅"),
  ("nothing.arrow.r", "⦳"),
  ("nothing.arrow.l", "⦴"),
  ("nothing.bar", "⦱"),
  ("nothing.circle", "⦲"),
  ("nothing.rev", "⦰"),
  ("without", "∖"),
  ("complement", "∁"),
  ("in", "∈"),
  ("in.not", "∉"),
  ("in.rev", "∋"),
  ("in.rev.not", "∌"),
  ("in.rev.small", "∍"),
  ("in.small", "∊"),
  ("subset", "⊂"),
  ("subset.dot", "⪽"),
  ("subset.double", "⋐"),
  ("subset.eq", "⊆"),
  ("subset.eq.not", "⊈"),
  ("subset.eq.sq", "⊑"),
  ("subset.eq.sq.not", "⋢"),
  ("subset.neq", "⊊"),
  ("subset.not", "⊄"),
  ("subset.sq", "⊏"),
  ("subset.sq.neq", "⋤"),
  ("supset", "⊃"),
  ("supset.dot", "⪾"),
  ("supset.double", "⋑"),
  ("supset.eq", "⊇"),
  ("supset.eq.not", "⊉"),
  ("supset.eq.sq", "⊒"),
  ("supset.eq.sq.not", "⋣"),
  ("supset.neq", "⊋"),
  ("supset.not", "⊅"),
  ("supset.sq", "⊐"),
  ("supset.sq.neq", "⋥"),
  ("union", "∪"),
  ("union.arrow", "⊌"),
  ("union.big", "⋃"),
  ("union.dot", "⊍"),
  ("union.dot.big", "⨃"),
  ("union.double", "⋓"),
  ("union.minus", "⩁"),
  ("union.or", "⩅"),
  ("union.plus", "⊎"),
  ("union.plus.big", "⨄"),
  ("union.sq", "⊔"),
  ("union.sq.big", "⨆"),
  ("union.sq.double", "⩏"),
  ("inter", "∩"),
  ("inter.and", "⩄"),
  ("inter.big", "⋂"),
  ("inter.dot", "⩀"),
  ("inter.double", "⋒"),
  ("inter.sq", "⊓"),
  ("inter.sq.big", "⨅"),
  ("inter.sq.double", "⩎"),
  ("infinity", "∞"),
  ("infinity.bar", "⧞"),
  ("infinity.incomplete", "⧜"),
  ("infinity.tie", "⧝"),
  ("oo", "∞"),
  ("partial", "∂"),
  ("gradient", "∇"),
  ("nabla", "∇"),
  ("sum", "∑"),
  ("sum.integral", "⨋"),
  ("product", "∏"),
  ("product.co", "∐"),
  ("integral", "∫"),
  ("integral.arrow.hook", "⨗"),
  ("integral.ccw", "⨑"),
  ("integral.cont", "∮"),
  ("integral.cont.ccw", "∳"),
  ("integral.cont.cw", "∲"),
  ("integral.cw", "∱"),
  ("integral.dash", "⨍"),
  ("integral.dash.double", "⨎"),
  ("integral.double", "∬"),
  ("integral.quad", "⨌"),
  ("integral.inter", "⨙"),
  ("integral.slash", "⨏"),
  ("integral.square", "⨖"),
  ("integral.surf", "∯"),
  ("integral.times", "⨘"),
  ("integral.triple", "∭"),
  ("integral.union", "⨚"),
  ("integral.vol", "∰"),
  ("laplace", "∆"),
  ("forall", "∀"),
  ("exists", "∃"),
  ("exists.not", "∄"),
  ("top", "⊤"),
  ("bot", "⊥"),
  ("not", "¬"),
  ("and", "∧"),
  ("and.big", "⋀"),
  ("and.curly", "⋏"),
  ("and.dot", "⟑"),
  ("and.double", "⩓"),
  ("or", "∨"),
  ("or.big", "⋁"),
  ("or.curly", "⋎"),
  ("or.dot", "⟇"),
  ("or.double", "⩔"),
  ("xor", "⊕"),
  ("xor.big", "⨁"),
  ("models", "⊧"),
  ("forces", "⊩"),
  ("forces.not", "⊮"),
  ("therefore", "∴"),
  ("because", "∵"),
  ("qed", "∎"),
  ("mapsto", "↦"),
  ("mapsto.long", "⟼"),
  ("compose", "∘"),
  ("compose.o", "⊚"),
  ("convolve", "∗"),
  ("convolve.o", "⊛"),
  ("multimap", "⊸"),
  ("multimap.double", "⧟"),
  ("tiny", "⧾"),
  ("miny", "⧿"),
  ("divides", "∣"),
  ("divides.not", "∤"),
  ("divides.not.rev", "⫮"),
  ("divides.struck", "⟊"),
  ("wreath", "≀"),
  ("angle", "∠"),
  ("angle.acute", "⦟"),
  ("angle.arc", "∡"),
  ("angle.arc.rev", "⦛"),
  ("angle.azimuth", "⍼"),
  ("angle.obtuse", "⦦"),
  ("angle.rev", "⦣"),
  ("angle.right", "∟"),
  ("angle.right.rev", "⯾"),
  ("angle.right.arc", "⊾"),
  ("angle.right.dot", "⦝"),
  ("angle.right.square", "⦜"),
  ("angle.s", "⦞"),
  ("angle.spatial", "⟀"),
  ("angle.spheric", "∢"),
  ("angle.spheric.rev", "⦠"),
  ("angle.spheric.t", "⦡"),
  ("angzarr", "⍼"),
  ("parallel", "∥"),
  ("parallel.struck", "⫲"),
  ("parallel.o", "⦷"),
  ("parallel.eq", "⋕"),
  ("parallel.equiv", "⩨"),
  ("parallel.not", "∦"),
  ("parallel.slanted.eq", "⧣"),
  ("parallel.slanted.eq.tilde", "⧤"),
  ("parallel.slanted.equiv", "⧥"),
  ("parallel.tilde", "⫳"),
  ("perp", "⟂"),
  ("perp.o", "⦹"),
)

// Every canonical name must resolve to the expected glyph in this Typst
// version and pass through math-once in both named raw and Typst-math input.
#for (name, expected) in symbols {
  let resolved = eval(name, mode: "math").body
  assert(resolved.text == expected, message: name)
  if name not in ("plus", "minus", "div", "times", "eq") {
    eq("x = " + name)
    if expected not in ("+", "−", "×", "⋅", "∗", "÷", "=") {
      eq("x = " + expected)
      eq($x = #resolved$)
    }
  }
}

// The five ordinary arithmetic/relation glyphs retain evaluator semantics.
#eq(`1 plus 2`)
#eq(`3 minus 2`)
#eq(`6 div 2`)
#eq(`2 times 3`)
#eq($1 + 2$)
#eq($3 - 2$)
#eq($6 div 2$)
#eq($2 times 3$)
#eq($x = 1$)

// Display-only symbols must never create a stored numeric result.
#eq(`ambiguous := infinity`)
#context assert("ambiguous" not in eq())
